name: Validate Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant
          pip install pytest
          pip install pytest-homeassistant-custom-component

      - name: Validate manifest
        run: |
          python -c "
          import json
          with open('custom_components/pawfit/manifest.json') as f:
              manifest = json.load(f)
          print(f'Domain: {manifest[\"domain\"]}')
          print(f'Version: {manifest[\"version\"]}')
          assert manifest['domain'] == 'pawfit'
          assert 'version' in manifest
          print('Manifest validation passed!')
          "

      - name: Check Python syntax
        run: |
          python -m py_compile custom_components/pawfit/*.py

      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            python -m pytest tests/ -v
          else
            echo "No tests directory found, skipping tests"
          fi

      - name: Validate HACS
        run: |
          python -c "
          import json
          with open('hacs.json') as f:
              hacs = json.load(f)
          print(f'HACS Name: {hacs[\"name\"]}')
          assert 'name' in hacs
          assert 'zip_release' in hacs
          print('HACS validation passed!')
          "
